[build-system]
requires = [
 "setuptools",
 "wheel",
 "numpy>=1.10",
 "Cython>=0.22",
 "scipy",
 "mdtraj",
 "pybind11",
 "deeptime",
 "deprecated"
 ]


# TODO: investigate: this does not ship versioneer.py from project root.
#build-backend = "setuptools.build_meta"
