
defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    #- image: continuumio/miniconda3
    - image: condaforge/linux-anvil

inst_conda_bld: &inst_conda_bld
  - run: conda config --add channels conda-forge
  - run: conda config --set always_yes true
  - run: conda config --set quiet true
  - run: conda install conda-build

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      #- run: conda config --add channels conda-forge
      #- run: conda config --set always_yes true
      #- run: conda config --set quiet true
      #- run: conda install conda-build
      - run: mkdir workspace
      - run: conda build devtools/conda-recipe --python=3.6 --no-test --output-folder workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - "*"

  test:
    <<: *defaults
    parallelism: 4
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PYTHONHASHSEED: 0
      OMP_NUM_THREADS: 1
      PYEMMA_NJOBS: 1

    steps:
      - checkout

      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      #- run: conda config --add channels conda-forge
      #- run: conda config --set always_yes true
      #- run: conda config --set quiet true
      #- run: conda install conda-build
      - attach_workspace:
          at: workspace
      - run: conda build devtools/conda-recipe --python=3.6 --test --output-folder workspace
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
