jobs:
- job:
  displayName: "OS X"
  pool:
    vmImage: 'macOS-11'
  strategy:
    matrix:
      Python38:
        CONDA_PY: '3.8'
        CONDA_NPY: '1.18'
      Python39:
        CONDA_PY: '3.9'
        CONDA_NPY: '1.19'
      Python10:
        CONDA_PY: '3.10'
        CONDA_NPY: '1.21'

  steps:
  - template: checkout.yml
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: sudo chmod -R 777 /usr/local/miniconda
    displayName: Fix Conda permissions
  - script: env

  - template: conda-setup+build.yml
  - template: test-results.yml
