jobs:
- job:
  displayName: Win
  pool:
    vmImage: "windows-2019"
  strategy:
    matrix:
      Python38:
        CONDA_PY: '3.8'
        CONDA_NPY: '1.18'
      Python39:
        CONDA_PY: '3.9'
        CONDA_NPY: '1.19'
      Python10:
        CONDA_PY: '3.10'
        CONDA_NPY: '1.21'

  steps:
  - template: checkout.yml
  - task: BatchScript@1
    inputs:
      filename: "$(CONDA)\\Scripts\\activate.bat"
      modifyEnvironment: True
    displayName: Add conda to PATH
  - template: conda-setup+build.yml
  - template: test-results.yml
