jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-22.04'
  timeoutInMinutes: 360

  strategy:
    matrix:
      Python38:
        CONDA_PY: '3.8'
        CONDA_NPY: '1.18'
      Python39:
        CONDA_PY: '3.9'
        CONDA_NPY: '1.19'
      Python10:
        CONDA_PY: '3.10'
        CONDA_NPY: '1.21'
 
    maxParallel: 10

  steps:
  - template: checkout.yml
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: sudo install -d -m 0777 /usr/envs
    displayName: Fix Conda permissions

  - template: conda-setup+build.yml
  - template: test-results.yml
